package team.chisel;

import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import com.tterrag.registrate.providers.RegistrateLangProvider;
import com.tterrag.registrate.providers.loot.RegistrateBlockLootTables;
import com.tterrag.registrate.util.entry.BlockEntry;

import net.minecraft.client.renderer.RenderType;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.data.recipes.ShapedRecipeBuilder;
import net.minecraft.data.recipes.ShapelessRecipeBuilder;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraft.world.level.material.Material;
import net.minecraft.world.level.material.MaterialColor;
import net.minecraft.world.level.storage.loot.IntRange;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.ApplyBonusCount;
import net.minecraft.world.level.storage.loot.functions.LimitCount;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;
import net.minecraftforge.common.Tags;
import net.minecraftforge.registries.ForgeRegistries;
import team.chisel.api.block.BlockCreator;
import team.chisel.api.block.ChiselBlockFactory;
import team.chisel.client.data.ModelTemplates;
import team.chisel.client.data.VariantTemplates;
import team.chisel.client.sound.ChiselSoundTypes;
import team.chisel.common.Reference;
import team.chisel.common.block.BlockCarvable;
import team.chisel.common.block.BlockCarvableCarpet;
import team.chisel.common.block.BlockCarvablePane;
import team.chisel.common.init.ChiselCompatTags;

public class Features {

    private static final ChiselBlockFactory _FACTORY = ChiselBlockFactory.newFactory(Chisel.registrate());
    
    public static final Map<String, BlockEntry<BlockCarvable>> ALUMINUM = _FACTORY.newType(Material.METAL, "metals/aluminum")
            .applyTag(BlockTags.BEACON_BASE_BLOCKS)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .setGroupName("Aluminum Block")
            .equivalentTo(ChiselCompatTags.STORAGE_BLOCKS_ALUMINUM)
            .initialProperties(() -> Blocks.IRON_BLOCK)
            .color(MaterialColor.COLOR_LIGHT_GRAY)
            .variations(VariantTemplates.METAL)
            .build();
    
    public static final Map<String, BlockEntry<BlockCarvable>> ANDESITE = _FACTORY.newType(Material.STONE, "andesite")
            .addBlock(Blocks.ANDESITE)
            .addBlock(Blocks.POLISHED_ANDESITE)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.ANDESITE)
            .variations(VariantTemplates.ROCK)
            .build();
    
    public static final Map<String, BlockEntry<BlockCarvable>> ANTIBLOCK = _FACTORY.newType(Material.STONE, "antiblock", (p, v) -> new BlockCarvable(p, v))
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .layer(() -> RenderType::cutout)
            .initialProperties(() -> Blocks.STONE)
            .color(MaterialColor.COLOR_RED) // TODO colors per variant?
            .variations(VariantTemplates.colors(ModelTemplates.twoLayerWithTop("antiblock", false), (prov, block) -> 
                    new ShapedRecipeBuilder(block, 8)
                        .pattern("SSS").pattern("SGS").pattern("SSS")
                        .define('S', Tags.Items.STONE)
                        .define('G', Tags.Items.DUSTS_GLOWSTONE)
                        .unlockedBy("has_glowstone", prov.has(Tags.Items.DUSTS_GLOWSTONE))
                        .save(prov)))
            .build();    

    public static final Map<String, BlockEntry<BlockCarvable>> BASALT = _FACTORY.newType(Material.STONE, "basalt")
            .addBlock(Blocks.BASALT)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.BASALT)
            .variations(VariantTemplates.ROCK)
            .build();
    public static final ImmutableList<WoodType> VANILLA_WOODS = ImmutableList.of(WoodType.OAK, WoodType.SPRUCE, WoodType.BIRCH, WoodType.ACACIA, WoodType.JUNGLE, WoodType.DARK_OAK);
 
    public static final Map<String, BlockEntry<BlockCarvable>> BRICKS = _FACTORY.newType(Material.STONE, "bricks")
            .addBlock(Blocks.BRICKS)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.BRICKS)
            .variations(VariantTemplates.ROCK)
            .build();
    
    public static final Map<String, BlockEntry<BlockCarvable>> BRONZE = _FACTORY.newType(Material.METAL, "metals/bronze")
            .applyTag(BlockTags.BEACON_BASE_BLOCKS)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_IRON_TOOL)
            .setGroupName("Bronze Block")
            .addTag(ChiselCompatTags.STORAGE_BLOCKS_BRONZE)
            .initialProperties(() -> Blocks.IRON_BLOCK)
            .color(MaterialColor.TERRACOTTA_ORANGE)
            .variations(VariantTemplates.METAL)
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> BROWNSTONE = _FACTORY.newType(Material.STONE, "brownstone")
            .variation("default")
                .recipe((prov, block) -> new ShapedRecipeBuilder(block, 4)
                        .pattern(" S ").pattern("SCS").pattern(" S ")
                        .define('S', Tags.Items.SANDSTONE)
                        .define('C', Items.CLAY_BALL)
                        .unlockedBy("has_clay", prov.has(Items.CLAY_BALL))
                        .save(prov))
            .next("block")
            .next("doubleslab")
                .model(ModelTemplates.cubeColumn("doubleslab-side", "block"))
            .next("blocks")
            .next("weathered")
            .next("weathered_block")
            .next("weathered_doubleslab")
                .model(ModelTemplates.cubeColumn("weathered_doubleslab-side", "weathered_block"))
            .next("weathered_blocks")
            .next("weathered_half")
                .model(ModelTemplates.cubeBottomTop("weathered_half-side", "default", "weathered"))
            .next("weathered_block_half")
                .model(ModelTemplates.cubeBottomTop("weathered_block_half-side", "block", "weathered_block"))
            .build(b -> b.sound(SoundType.STONE).strength(1.0f));
    //BlockSpeedHandler.speedupBlocks.add(b);

    public static final Map<DyeColor, Map<String, BlockEntry<BlockCarvableCarpet>>> CARPET = Arrays.stream(DyeColor.values())
            .collect(Collectors.toMap(Function.identity(), color -> _FACTORY.newType(Material.WOOL, "carpet/" + (color.getSerializedName()), BlockCarvableCarpet::new)
                    .addBlock(new ResourceLocation(color.getSerializedName() + "_carpet")) // TODO improve this copied RL construction
                    .setGroupName(RegistrateLangProvider.toEnglishName(color.getSerializedName()) + " Carpet")
                    .model((prov, block) ->
                        prov.simpleBlock(block, prov.models()
                                .carpet("block/" + ModelTemplates.name(block), prov.modLoc("block/" + ModelTemplates.name(block).replace("carpet", "wool")))
                                .texture("particle", "#wool")))
                    .initialProperties(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(color.getSerializedName() + "_carpet")))
                    .variation("legacy")
                    .next("llama")
                    .build()));

    public static final Map<String, BlockEntry<BlockCarvable>> CHARCOAL = _FACTORY.newType(Material.STONE, "charcoal")
            .equivalentTo(ChiselCompatTags.STORAGE_BLOCKS_CHARCOAL)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .initialProperties(() -> Blocks.COAL_BLOCK)
            .variation(VariantTemplates.withRecipe(VariantTemplates.RAW, (prov, block) -> new ShapelessRecipeBuilder(block, 1)
                    .requires(Items.CHARCOAL, 9)
                    .unlockedBy("has_charcoal", prov.has(Items.CHARCOAL))
                    .save(prov)))
            .variations(VariantTemplates.ROCK)
            .build();
    
    public static final Map<String, BlockEntry<BlockCarvable>> COAL = _FACTORY.newType(Material.STONE, "coal")
            .equivalentTo(Tags.Blocks.STORAGE_BLOCKS_COAL)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .initialProperties(() -> Blocks.COAL_BLOCK)
            .variations(/*VariantTemplates.withUncraft(*/VariantTemplates.ROCK/*, Items.COAL)*/) // TODO
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> CLOUD = _FACTORY.newType(Material.CLOTH_DECORATION, "cloud")
            .variation("cloud")
            .next("large")
            .next("vertical")
            .next("grid")
            .build(b -> b.sound(SoundType.WOOL).explosionResistance(0.3F));

    public static final Map<String, BlockEntry<BlockCarvable>> COBBLESTONE = _FACTORY.newType(Material.STONE, "cobblestone")
            .addBlock(Blocks.COBBLESTONE)
            .applyTag(Tags.Blocks.COBBLESTONE)
            .applyTag(ItemTags.STONE_TOOL_MATERIALS)
            .applyTag(ItemTags.STONE_CRAFTING_MATERIALS)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.COBBLESTONE)
            .variations(VariantTemplates.COBBLESTONE)
            .build();
    
    public static final Map<String, BlockEntry<BlockCarvable>> COBBLESTONE_MOSSY = _FACTORY.newType(Material.STONE, "mossy_cobblestone")
            .addBlock(Blocks.MOSSY_COBBLESTONE)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(Tags.Blocks.COBBLESTONE_MOSSY)
            .initialProperties(() -> Blocks.MOSSY_COBBLESTONE)
            .variations(VariantTemplates.COBBLESTONE_MOSSY)
            .build();

    public static final Map<DyeColor, Map<String, BlockEntry<BlockCarvable>>> CONCRETE = Arrays.stream(DyeColor.values())
            .collect(Collectors.toMap(Function.identity(), color -> _FACTORY.newType(Material.STONE, "concrete/" + color.getSerializedName())
                    .addBlock(new ResourceLocation(color.getSerializedName() + "_concrete")) // TODO improve this copied RL construction
                    .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
                    .setGroupName(RegistrateLangProvider.toEnglishName(color.getSerializedName()) + " Concrete")
                    .initialProperties(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(color.getSerializedName() + "_concrete")))
                    .variations(VariantTemplates.ROCK)
                    .build()));
//  BlockSpeedHandler.speedupBlocks.add(b);

//    public static final Map<String, BlockEntry<BlockCarvable>> COPPER = _FACTORY.newType(Material.METAL, "copper")
//            .addBlock(Blocks.COPPER_BLOCK)
//            .applyTag(BlockTags.BEACON_BASE_BLOCKS)
//            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
//            .applyTag(BlockTags.NEEDS_IRON_TOOL)
//            .setGroupName("Copper Block")
//            .addTag(Tags.Blocks.STORAGE_BLOCKS_COPPER)
//            .initialProperties(() -> Blocks.COPPER_BLOCK)
//            .color(MaterialColor.COLOR_ORANGE)
//            .variations(VariantTemplates.METAL)
//            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> DIABASE = _FACTORY.newType(Material.STONE, "diabase")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .initialProperties(() -> Blocks.BASALT)
            .variation(VariantTemplates.RAW)
            .variations(VariantTemplates.ROCK)
            .addTag(ChiselCompatTags.STONE_DIABASE)
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> DIAMOND = _FACTORY.newType(Material.METAL, "diamond")
            .addBlock(Blocks.DIAMOND_BLOCK)
            .equivalentTo(Tags.Blocks.STORAGE_BLOCKS_DIAMOND)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_IRON_TOOL)
            .applyTag(BlockTags.BEACON_BASE_BLOCKS)
            .initialProperties(() -> Blocks.DIAMOND_BLOCK)
            .variation("terrain_diamond_embossed")
                .model(ModelTemplates.cubeColumn())
            .next("terrain_diamond_gem")
                .model(ModelTemplates.cubeColumn())
            .next("terrain_diamond_cells")
            .next("terrain_diamond_space")
            .next("terrain_diamond_spaceblack")
            .next("terrain_diamond_simple")
                .model(ModelTemplates.cubeColumn())
            .next("terrain_diamond_bismuth")
            .next("terrain_diamond_crushed")
            .next("terrain_diamond_four")
            .next("terrain_diamond_fourornate")
            .next("terrain_diamond_zelda")
            .next("terrain_diamond_ornatelayer")
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> DIORITE = _FACTORY.newType(Material.STONE, "diorite")
            .addBlock(Blocks.DIORITE)
            .addBlock(Blocks.POLISHED_DIORITE)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.DIORITE)
            .variations(VariantTemplates.ROCK)
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> EMERALD = _FACTORY.newType(Material.METAL, "emerald")
            .equivalentTo(Tags.Blocks.STORAGE_BLOCKS_EMERALD)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_IRON_TOOL)
            .applyTag(BlockTags.BEACON_BASE_BLOCKS)
            .initialProperties(() -> Blocks.EMERALD_BLOCK)
            /*.recipe((prov, block) -> new ShapelessRecipeBuilder(Items.EMERALD, 9)
                    .addIngredient(block)
                    .addCriterion("has_emerald_block", prov.hasItem(block))
                    .build(prov)) TODO: Match recipe seen in FeaturesOld*/
            .variation("panel")
            .next("panelclassic")
            .next("smooth")
            .next("chunk")
            .next("goldborder")
            .next("zelda")
            .next("cell")
            .next("cellbismuth")
            .next("four")
            .next("fourornate")
            .next("ornate")
            .next("masonryemerald")
            .next("emeraldcircle")
            .next("emeraldprismatic")
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> ENDSTONE = _FACTORY.newType(Material.STONE, "end_stone")
            .equivalentTo(Tags.Blocks.END_STONES)
            .addBlock(Blocks.END_STONE_BRICKS)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .initialProperties(() -> Blocks.END_STONE)
            .variations(VariantTemplates.ROCK)
            .build();

    public static final TagKey<Block> FACTORY1 = BlockTags.create(new ResourceLocation(Reference.MOD_ID, "factory"));

    public static final Map<String, BlockEntry<BlockCarvable>> FACTORY = _FACTORY.newType(Material.METAL, "factory")
            .setGroup(FACTORY1)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .initialProperties(() -> Blocks.IRON_BLOCK)
            .color(MaterialColor.TERRACOTTA_BROWN)
            .variation("dots")
                .recipe((prov, block) -> new ShapedRecipeBuilder(block, 32)
                        .pattern("SXS").pattern("X X").pattern("SXS")
                        .define('S', Tags.Items.STONE)
                        .define('X', Tags.Items.INGOTS_IRON)
                        .unlockedBy("has_iron", prov.has(Tags.Items.INGOTS_IRON))
                        .save(prov))
            .next("rust2")
            .next("rust")
            .next("platex")
            .next("wireframewhite")
            .next("wireframe")
            .next("hazard")
            .next("hazardorange")
            .next("circuit")
            .next("metalbox")
                .model(ModelTemplates.cubeColumn())
            .next("goldplate")
            .next("goldplating")
            .next("grinder")
            .next("plating")
            .next("rustplates")
            .next("column")
                .model(ModelTemplates.cubeColumn())
            .next("frameblue")
            .next("iceiceice")
            .next("tilemosaic")
            .next("vent")
                .model(ModelTemplates.cubeColumn())
            .next("wireframeblue")
            .build(b -> b.sound(ChiselSoundTypes.METAL));

    public static final Map<String, BlockEntry<BlockCarvable>> FUTURA = _FACTORY.newType(Material.STONE, "futura")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .recipe((prov, block) -> new ShapedRecipeBuilder(block, 8)
                .pattern("SSS").pattern("SGS").pattern("SSS")
                .define('S', Tags.Items.STONE)
                .define('G', Tags.Items.DUSTS_REDSTONE)
                .unlockedBy("has_redstone", prov.has(Tags.Items.DUSTS_REDSTONE))
                .save(prov))
            .initialProperties(() -> Blocks.STONE)
            .color(MaterialColor.COLOR_YELLOW)
            .variation("screen_metallic")
                .model(ModelTemplates.twoLayerTopShaded("screen_metallic", "screen_discoherent"))
            .next("screen_cyan")
                .model(ModelTemplates.twoLayerTopShaded("screen_cyan", "screen_discoherent"))
            .next("controller")
                .model(ModelTemplates.threeLayerTopShaded("controller_particle", "lines_plating", "rainbow_lines", "lines_invalid"))
            .next("wavy")
                .model(ModelTemplates.twoLayerTopShaded("rainbow_wave_particle", "rainbow_wave_base", "rainbow_wave"))
            .next("controller_purple")
                .model(ModelTemplates.threeLayerTopShaded("controller_unity_particle", "unity_lines_plating", "unity_lines", "lines_invalid"))
            .next("uber_wavy")
                .model(ModelTemplates.threeLayerTopShaded("orange_frame_particle", "orange_frame", "uber_rainbow", "screen_discoherent"))
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> GLASS = _FACTORY.newType(Material.GLASS, "glass")
            .addBlock(Blocks.GLASS)
            .addTag(Tags.Blocks.GLASS)
            .addTag(Tags.Blocks.GLASS_COLORLESS)
            .initialProperties(() -> Blocks.GLASS)
            .variation("terrain_glassbubble")
//            .next("chinese")
            .next("japanese")
            .next("terrain_glassdungeon")
            .next("terrain_glasslight")
            .next("terrain_glassnoborder")
            .next("terrain_glass_ornatesteel")
            .next("terrain_glass_screen")
            .next("terrain_glassshale")
            .next("terrain_glass_steelframe")
            .next("terrain_glassstone")
            .next("terrain_glassstreak")
            .next("terrain_glass_thickgrid")
            .next("terrain_glass_thingrid")
            .next("a1_glasswindow_ironfencemodern")
            .next("chrono")
            .next("chinese2")
            .next("japanese2")
            .build(b -> b.sound(SoundType.GLASS).explosionResistance(0.3F));

    public static final Map<String, BlockEntry<BlockCarvablePane>> GLASSPANE = _FACTORY.newType(Material.GLASS, "glasspane", BlockCarvablePane::new)
            .addBlock(Blocks.GLASS_PANE)
            .addTag(Tags.Blocks.GLASS)
            .addTag(Tags.Blocks.GLASS_COLORLESS)
            .initialProperties(() -> Blocks.GLASS)
            .variation("terrain_glassbubble")
                .model(ModelTemplates.paneBlockCTM("block/glass/edge"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
//            .next("chinese")
//                .model(ModelTemplates.paneblock("block/glass/chinese-top"))
//                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("japanese")
                .model(ModelTemplates.paneBlock("block/glass/japanese-top"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("terrain_glassdungeon")
                .model(ModelTemplates.paneBlock("block/glass/edge_steel"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("terrain_glasslight")
                .model(ModelTemplates.paneBlockCTM("block/glass/edge"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("terrain_glassnoborder")
                .model(ModelTemplates.paneBlockCTM("block/glass/edge"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("terrain_glass_ornatesteel")
                .model(ModelTemplates.paneBlockCTM("block/glass/edge_steel"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("terrain_glass_screen")
                .model(ModelTemplates.paneBlock("block/glass/terrain_glass_screen"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("terrain_glassshale")
                .model(ModelTemplates.paneBlockCTM("block/glass/edge_steel"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("terrain_glass_steelframe")
                .model(ModelTemplates.paneBlockCTM("block/glass/edge_steel"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("terrain_glassstone")
                .model(ModelTemplates.paneBlockCTM("block/glass/edge_steel"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("terrain_glassstreak")
                .model(ModelTemplates.paneBlock("block/glass/terrain_glassstreak-top"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("terrain_glass_thickgrid")
                .model(ModelTemplates.paneBlock("block/glass/terrain_glass_thickgrid"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("terrain_glass_thingrid")
                .model(ModelTemplates.paneBlock("block/glass/terrain_glass_thingrid"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("a1_glasswindow_ironfencemodern")
                .model(ModelTemplates.paneBlock("block/glass/edge_steel"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("chrono")
                .model(ModelTemplates.paneBlockCTM("block/glass/edge_steel"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("chinese2")
                .model(ModelTemplates.paneBlock("block/glass/chinese2-top"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .next("japanese2")
                .model(ModelTemplates.paneBlock("block/glass/japanese2-top"))
                .itemModel((ctx, prov) -> prov.withExistingParent("item/" + prov.name(ctx::getEntry), new ResourceLocation("item/generated")).texture("layer0", "block/" + prov.name(ctx::getEntry).replaceFirst("pane", "")))
            .build(b -> b.sound(SoundType.GLASS).explosionResistance(0.3F));

    public static Map<DyeColor, Map<String, BlockEntry<BlockCarvable>>> GLASS_STAINED = Arrays.stream(DyeColor.values())
            .collect(Collectors.toMap(Function.identity(), color -> _FACTORY.newType(Material.GLASS, "glass_stained/" + color.getSerializedName())
                 .addBlock(new ResourceLocation(color.getSerializedName() + "_stained_glass"))
                 .setGroupName(RegistrateLangProvider.toEnglishName(color.getSerializedName()) + " Stained Glass")
                 .initialProperties(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(color.getSerializedName() + "_stained_glass")))
                 .addTag(Tags.Blocks.GLASS)
                 .addTag(BlockTags.create(new ResourceLocation("forge", "glass_" + color.getSerializedName())))
                 .variation("panel")
                 .next("framed")
                    .model(ModelTemplates.cubeCTMTranslusent("block/glass_stained/" + color.getSerializedName() + "/framed", "block/glass_stained/" + color.getSerializedName() + "/framed_ct"))
                 .next("framed_fancy")
                    .model(ModelTemplates.cubeCTMTranslusent("block/glass_stained/" + color.getSerializedName() + "/framed", "block/glass_stained/" + color.getSerializedName() + "/framed_fancy_ct"))
                 .next("streaks")
                 .next("rough")
                 .next("brick")
                 .build(b -> b.sound(SoundType.GLASS).explosionResistance(0.3F))
            ));

    //stained glass pane

    public static final Map<String, BlockEntry<BlockCarvable>> GLOWSTONE = _FACTORY.newType(Material.GLASS, "glowstone")
            .addBlock(Blocks.GLOWSTONE)
            .loot((prov, block) -> prov.add(block, RegistrateBlockLootTables.createSilkTouchDispatchTable(block,
                RegistrateBlockLootTables.applyExplosionDecay(block,
                    LootItem.lootTableItem(Items.GLOWSTONE_DUST)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 4.0F)))
                        .apply(ApplyBonusCount.addUniformBonusCount(Enchantments.BLOCK_FORTUNE))
                        .apply(LimitCount.limitCount(IntRange.range(1, 4)))))))
            .initialProperties(() -> Blocks.GLOWSTONE)
            .variations(VariantTemplates.STONE)
            .variation("extra/bismuth").localizedName("Bismuth")
            .next("extra/tiles_large_bismuth").localizedName("Tiles Large Bismuth")
            .next("extra/tiles_medium_bismuth").localizedName("Tiles Medium Bismuth")
            .next("extra/neon").localizedName("Neon")
            .next("extra/neon_panel").localizedName("Neon Panel")
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> GOLD = _FACTORY.newType(Material.METAL, "metals/gold")
            .applyTag(BlockTags.BEACON_BASE_BLOCKS)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_IRON_TOOL)
            .setGroupName("Gold Block")
            .addTag(Tags.Blocks.STORAGE_BLOCKS_GOLD)
            .initialProperties(() -> Blocks.GOLD_BLOCK)
            .color(MaterialColor.GOLD)
            .variations(VariantTemplates.METAL)
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> GOLD_TERRAIN = _FACTORY.newType(Material.METAL, "gold")
            .addBlock(Blocks.GOLD_BLOCK)
            .addTag(Tags.Blocks.STORAGE_BLOCKS_GOLD)
            .initialProperties(() -> Blocks.GOLD_BLOCK)
            .applyTag(BlockTags.NEEDS_IRON_TOOL)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .variation("terrain_gold_largeingot")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_smallingot")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_brick")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_cart")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_coin_heads")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_coin_tails")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_crate_dark")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_crate_light")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_plates")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_rivets")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_star")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_space")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_spaceblack")
                .model(ModelTemplates.cubeBottomTop())
            .next("terrain_gold_simple")
                .model(ModelTemplates.cubeBottomTop())
            .next("goldeye")
            .build(b-> b.sound(ChiselSoundTypes.METAL).strength(3.0F).explosionResistance(10.0F).requiresCorrectToolForDrops());

    public static final Map<String, BlockEntry<BlockCarvable>> GRANITE = _FACTORY.newType(Material.STONE, "granite")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.GRANITE)
            .variations(VariantTemplates.ROCK)
            .addBlock(Blocks.GRANITE)
            .addBlock(Blocks.POLISHED_GRANITE)
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> HEX_PLATING = _FACTORY.newType(Material.STONE, "hexplating")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .initialProperties(() -> Blocks.STONE)
            .variation("hexbase")
            .next("hexnew")
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> ICE = _FACTORY.newType(Material.ICE, "ice")
            .addBlock(Blocks.ICE)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .addTag(BlockTags.ICE)
            .variations(VariantTemplates.ROCK).opaque(false)
            .initialProperties(() -> Blocks.ICE)
            .build(b -> b.strength(0.5F).lightLevel(value -> 3).sound(SoundType.GLASS).requiresCorrectToolForDrops());

    public static final Map<String, BlockEntry<BlockCarvable>> IRON = _FACTORY.newType(Material.METAL, "iron")
            .addBlock(Blocks.IRON_BLOCK)
            .initialProperties(() -> Blocks.IRON_BLOCK)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_IRON_TOOL)
            .applyTag(BlockTags.BEACON_BASE_BLOCKS)
            .addTag(Tags.Blocks.STORAGE_BLOCKS_IRON)
            //.variations(VariantTemplates.METAL)
            .variations(VariantTemplates.METAL_TERRAIN)
            .variation("moon")
                .model(ModelTemplates.cubeBottomTop())
            .next("vents")
                .model(ModelTemplates.cubeColumn())
            .build(b-> b.sound(SoundType.METAL).strength(5.0f).requiresCorrectToolForDrops());

    public static final Map<String, BlockEntry<BlockCarvable>> LABORATORY = _FACTORY.newType(Material.STONE, "laboratory")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .recipe((prov, block) -> new ShapedRecipeBuilder(block, 8)
                    .pattern("***").pattern("*X*").pattern("***")
                    .define('*', Blocks.STONE)
                    .define('X', Items.QUARTZ)
                    .unlockedBy("has_quartz", prov.has(Items.QUARTZ))
                    .save(prov))
            .initialProperties(() -> Blocks.STONE)
            .color(MaterialColor.SNOW)
            .variation("wallpanel")
            .next("dottedpanel")
            .next("roundel")
            .next("wallvents")
                .model(ModelTemplates.cubeColumn())
            .next("largetile")
            .next("smalltile")
            .next("floortile")
            .next("checkertile")
            .next("fuzzscreen")
            .next("largesteel")
                .model(ModelTemplates.cubeColumn())
            .next("smallsteel")
                .model(ModelTemplates.cubeColumn())
            .next("directionleft")
                .model(ModelTemplates.cubeColumn())
            .next("directionright")
                .model(ModelTemplates.cubeColumn())
            .next("infocon")
                .model(ModelTemplates.cubeColumn())
            .build(b -> b.sound(ChiselSoundTypes.METAL));

    public static final Map<String, BlockEntry<BlockCarvable>> LAPIS = _FACTORY.newType(Material.STONE, "lapis")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_IRON_TOOL)
            .addTag(Tags.Blocks.STORAGE_BLOCKS_LAPIS)
            .addBlock(Blocks.LAPIS_BLOCK)
            .initialProperties(() -> Blocks.LAPIS_BLOCK)
            .variation("terrain_lapisblock_chunky")
            .next("terrain_lapisblock_panel")
            .next("terrain_lapisblock_zelda")
            .next("terrain_lapisornate")
            .next("terrain_lapistile")
            .next("a1_blocklapis_panel")
            .next("a1_blocklapis_smooth")
            .next("a1_blocklapis_ornatelayer")
            .next("masonrylapis")
            .build(b-> b.strength(3.0F).explosionResistance(5.0F).sound(SoundType.STONE).requiresCorrectToolForDrops());

    public static final Map<String, BlockEntry<BlockCarvable>> LAVASTONE = _FACTORY.newType(Material.STONE, "lavastone")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .addTag(ChiselCompatTags.LAVASTONE)
            .initialProperties(() -> Blocks.STONE)
            .recipe((prov, block) -> new ShapedRecipeBuilder(block, 8)
                    .pattern("***").pattern("*X*").pattern("***")
                    .define('*', Blocks.STONE)
                    .define('X', Items.LAVA_BUCKET)
                    .unlockedBy("has_stone", prov.has(Items.STONE))
                    .save(prov))
            .variation("cracked")
                .model(ModelTemplates.fluidCube("lava"))
            .next("soft_bricks").localizedName("Weathered Bricks")
                .model(ModelTemplates.fluidCube("lava"))
            .next("cracked")
                .model(ModelTemplates.fluidCube("lava"))
            .next("triple_bricks").localizedName("Wide Bricks")
                .model(ModelTemplates.fluidCube("lava"))
            .next("encased_bricks")
                .model(ModelTemplates.fluidPassCube("lava"))
            .next("braid")
                .model(ModelTemplates.fluidCube("lava"))
            .next("array").localizedName("Arrayed Bricks")
                .model(ModelTemplates.fluidPassCube("lava"))
            .next("tiles_large").localizedName("Big Tile")
                .model(ModelTemplates.fluidPassCube("lava"))
            .next("tiles_small").localizedName("Small Tiles")
                .model(ModelTemplates.fluidCube("lava"))
            .next("chaotic_medium").localizedName("Disordered Tiles")
                .model(ModelTemplates.fluidCube("lava"))
            .next("chaotic_small").localizedName("Small Disordered Tiles")
                .model(ModelTemplates.fluidCube("lava"))
            .next("dent")
                .model(ModelTemplates.fluidPassCube("lava"))
            .next("french_1")
                .model(ModelTemplates.fluidCube("lava"))
            .next("french_2")
                .model(ModelTemplates.fluidCube("lava"))
            .next("jellybean")
                .model(ModelTemplates.fluidPassCube("lava"))
            .next("layers")
                .model(ModelTemplates.fluidCube("lava"))
            .next("mosaic")
                .model(ModelTemplates.fluidPassCube("lava"))
            .next("ornate")
                .model(ModelTemplates.fluidCube("lava"))
            .next("panel")
                .model(ModelTemplates.fluidCube("lava"))
            .next("road")
                .model(ModelTemplates.fluidCube("lava"))
            .next("slanted")
                .model(ModelTemplates.fluidPassCube("lava"))
            .next("zag")
                .model(ModelTemplates.fluidPassCube("lava"))
            .next("circularct").localizedName("Circular")
                .model(ModelTemplates.fluidCubeCTM("lava", "circular"))
            .next("weaver").localizedName("Celtic")
                .model(ModelTemplates.fluidPassCube("lava"))
            .next("solid_bricks").localizedName("Bricks")
                .model(ModelTemplates.fluidCube("lava"))
            .next("small_bricks")
                .model(ModelTemplates.fluidCube("lava"))
            .next("circular")
                .model(ModelTemplates.fluidCube("lava"))
            .next("tiles_medium").localizedName("Tiles")
                .model(ModelTemplates.fluidPassCube("lava"))
            .next("pillar")
                .model(ModelTemplates.fluidPassColume("lava"))
            .next("twisted")
                .model(ModelTemplates.fluidPassColume("lava"))
            .next("prism")
                .model(ModelTemplates.fluidCube("lava"))
            .next("chaotic_bricks").localizedName("Trodden Bricks")
                .model(ModelTemplates.fluidPassCube("lava"))
            .next("cuts")
                .model(ModelTemplates.fluidPassCube("lava"))
            .build(b -> b.strength(4.0F).explosionResistance(50.0F).sound(SoundType.STONE));

    public static final Map<String, BlockEntry<BlockCarvable>> LIMESTONE = _FACTORY.newType(Material.STONE, "limestone")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.STONE)
            .color(MaterialColor.TERRACOTTA_GREEN)
            .variation(VariantTemplates.RAW)
            .variations(VariantTemplates.ROCK)
            .addTag(ChiselCompatTags.STONE_LIMESTONE)
            .build(b -> b.strength(1F, 5F));

    public static final Map<String, BlockEntry<BlockCarvable>> MARBLE = _FACTORY.newType(Material.STONE, "marble")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.STONE)
            .color(MaterialColor.QUARTZ)
            .variation(VariantTemplates.RAW)
            .variations(VariantTemplates.ROCK)
            .addTag(ChiselCompatTags.STONE_MARBLE)
            .build(b -> b.strength(1.75F, 10.0F));

    public static final Map<WoodType, Map<String, BlockEntry<BlockCarvable>>> PLANKS = VANILLA_WOODS.stream()
            .map(t -> Pair.of(t, new ResourceLocation(t.name() + "_planks")))
            .collect(Collectors.toMap(Pair::getFirst, pair -> _FACTORY.newType(Material.WOOD, "planks/" + pair.getFirst().name())
                    .addBlock(pair.getSecond())
                    .applyTag(BlockTags.MINEABLE_WITH_AXE)
                    .applyTag(BlockTags.PLANKS)
                    .setGroupName(RegistrateLangProvider.toEnglishName(pair.getFirst().name()) + " Planks")
                    .initialProperties(() -> ForgeRegistries.BLOCKS.getValue(pair.getSecond()))
                    .variations(VariantTemplates.PLANKS)
                    .build()));

    // TODO Temp Merge with above once 1.16 hits
    /*public static final Map<String, Map<String, BlockEntry<BlockCarvable>>> PLANKS_116 = ImmutableList.of("crimson", "warped").stream()
            .map(t -> Pair.of(t, new ResourceLocation(t + "_planks")))
            .collect(Collectors.toMap(Pair::getFirst, pair -> _FACTORY.newType(Material.WOOD, "planks/" + pair.getFirst())
                    .addBlock(pair.getSecond())
                    .setGroupName(RegistrateLangProvider.toEnglishName(pair.getFirst()) + " Planks")
                    .variations(VariantTemplates.PLANKS)
                    .build($ -> Block.Properties.from(ForgeRegistries.BLOCKS.getValue(pair.getSecond())))));//*/

    public static final Map<String, BlockEntry<BlockCarvable>> PRISMARINE = _FACTORY.newType(Material.STONE, "prismarine")
            .addBlock(Blocks.PRISMARINE)
            .addBlock(Blocks.PRISMARINE_BRICKS)
            .addBlock(Blocks.DARK_PRISMARINE)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.PRISMARINE)
            .variations(VariantTemplates.ROCK)
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> PURPUR = _FACTORY.newType(Material.STONE, "purpur")
            .addBlock(Blocks.PURPUR_BLOCK)
            .addBlock(Blocks.PURPUR_PILLAR)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.PURPUR_BLOCK)
            .variations(VariantTemplates.ROCK)
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> QUARTZ = _FACTORY.newType(Material.STONE, "quartz")
            .equivalentTo(Tags.Blocks.STORAGE_BLOCKS_QUARTZ)
            .addBlock(Blocks.QUARTZ_PILLAR)
            .addBlock(Blocks.CHISELED_QUARTZ_BLOCK)
            .addBlock(Blocks.SMOOTH_QUARTZ)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.QUARTZ_BLOCK)
            .variations(VariantTemplates.ROCK)
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> RED_SANDSTONE = _FACTORY.newType(Material.STONE, "red_sandstone")
            .addBlock(Blocks.RED_SANDSTONE)
            .addBlock(Blocks.CHISELED_RED_SANDSTONE)
            .addBlock(Blocks.CUT_RED_SANDSTONE)
            .addBlock(Blocks.SMOOTH_RED_SANDSTONE)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(Tags.Blocks.SANDSTONE)
            .initialProperties(() -> Blocks.SANDSTONE)
            .color(MaterialColor.COLOR_ORANGE)
            .variations(VariantTemplates.ROCK)
            .variation("extra/bevel_skeleton").localizedName("Bevel Skeleton")
            .next("extra/glyphs").localizedName("Glyphs")
            .next("extra/small").localizedName("Small")
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> REDSTONE = _FACTORY.newType(Material.METAL, "redstone", BlockCreators.redstoneCreator)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .equivalentTo(Tags.Blocks.STORAGE_BLOCKS_REDSTONE)
            .initialProperties(() -> Blocks.REDSTONE_BLOCK)
            .variations(VariantTemplates.STONE)
            .build(); //TODO: Recipe from FeaturesOld

    public static final Map<String, BlockEntry<BlockCarvable>> SANDSTONE = _FACTORY.newType(Material.STONE, "sandstone")
            .addBlock(Blocks.SANDSTONE)
            .addBlock(Blocks.CHISELED_SANDSTONE)
            .addBlock(Blocks.CUT_SANDSTONE)
            .addBlock(Blocks.SMOOTH_SANDSTONE)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(Tags.Blocks.SANDSTONE)
            .initialProperties(() -> Blocks.SANDSTONE)
            .variations(VariantTemplates.ROCK)
            .variation("extra/bevel_creeper").localizedName("Bevel Creeper")
            .next("extra/glyphs").localizedName("Glyphs")
            .next("extra/small").localizedName("Small")
            //TODO: column-ctm
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> STONE_BRICKS = _FACTORY.newType(Material.STONE, "stone_bricks")
            .addBlock(Blocks.STONE)
            .addBlock(Blocks.STONE_BRICKS)
            .addBlock(Blocks.CHISELED_STONE_BRICKS)
            .addBlock(Blocks.CRACKED_STONE_BRICKS)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.STONE_BRICKS)
            .variations(VariantTemplates.ROCK)
            .variation("extra/largeornate").localizedName("Large Ornate")
            .next("extra/poison").localizedName("Poison")
            .next("extra/sunken").localizedName("Sunken")
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> TERRACOTTA = _FACTORY.newType(Material.STONE, "terracotta")
            .addBlock(Blocks.TERRACOTTA)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .initialProperties(() -> Blocks.TERRACOTTA)
            .variations(VariantTemplates.ROCK)
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> TECHNICAL = _FACTORY.newType(Material.METAL, "technical")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .setGroup(FACTORY1)
            .setGroupName("")
            .initialProperties(() -> Blocks.IRON_BLOCK)
            .color(MaterialColor.TERRACOTTA_LIGHT_GRAY)
            .variation("scaffold")
            .next("cautiontape")
            .next("industrialrelic")
            .next("pipeslarge")
            .next("fanfast")
                .model(ModelTemplates.cubeColumn())
            .next("pipessmall")
            .next("fanstill")
                .model(ModelTemplates.cubeColumn())
            .next("vent")
            .next("ventglowing")
            .next("insulationv2")
            .next("spinningstuffanim")
            .next("cables")
            .next("rustyboltedplates")
            .next("grate")
            .next("malfunctionfan")
                .model(ModelTemplates.cubeColumn())
            .next("graterusty")
            .next("scaffoldtransparent").opaque(false)
            .next("fanfasttransparent")
                .opaque(false)
                .model(ModelTemplates.cubeColumn())
            .next("fanstilltransparent")
                .model(ModelTemplates.cubeColumn())
                .opaque(false)
            .next("massivefan")
            .next("massivehexplating")
            .build(b -> b.sound(SoundType.METAL));

    public static final Map<String, BlockEntry<BlockCarvable>> TECHNICAL_NEW = _FACTORY.newType(Material.METAL, "technical/new")
            .setGroup(FACTORY1)
            .setGroupName("")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .initialProperties(() -> Blocks.IRON_BLOCK)
            .color(MaterialColor.TERRACOTTA_LIGHT_GRAY)
            .variation("weatheredgreenpanels")
            .next("weatheredorangepanels")
            .next("sturdy")
            .next("megacell")
                .model(ModelTemplates.cubeBottomTop())
            .next("exhaustplating")
            .next("makeshiftpanels")
            .next("engineering")
            .next("scaffoldlarge")
            .next("piping")
            .next("oldetimeyserveranim")
            .next("tapedrive")
            .build(b -> b.sound(SoundType.METAL));

    public static final TagKey<Block> TEMPLE1 = BlockTags.create(new ResourceLocation(Reference.MOD_ID, "temple"));

    public static final Map<String, BlockEntry<BlockCarvable>> TEMPLE = _FACTORY.newType(Material.STONE, "temple")
            .setGroup(TEMPLE1)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .recipe((prov, block) -> new ShapedRecipeBuilder(block, 32)
                    .pattern("SSS").pattern("SXS").pattern("SSS")
                    .define('S', Tags.Items.STONE)
                    .define('X', Tags.Items.DYES_CYAN)
                    .unlockedBy("has_dye", prov.has(Tags.Items.DYES_CYAN))
                    .save(prov))
            .variation("cobble") //TODO fix ctm and model
                .model(ModelTemplates.cubeEldritch())
            .next("ornate")
                .model(ModelTemplates.cubeEldritch())
            .next("plate")
                .model(ModelTemplates.cubeEldritch())
            .next("plate_cracked") //TODO fix ctm and model
                .model(ModelTemplates.cubeEldritch())
            .next("bricks")
                .model(ModelTemplates.cubeEldritch())
            .next("large_bricks")
                .model(ModelTemplates.cubeEldritch())
            .next("weared_bricks")
                .model(ModelTemplates.cubeEldritch())
            .next("disarray_bricks")
                .model(ModelTemplates.cubeEldritch())
            .next("column")
                .model(ModelTemplates.columnEldritch("temple"))
            .next("stand")
                .model(ModelTemplates.columnEldritch("temple"))
            .next("tiles")
                .model(ModelTemplates.cubeEldritch())
            .next("smalltiles")
                .model(ModelTemplates.cubeEldritch())
            .next("tiles_light")
                .model(ModelTemplates.cubeEldritch())
            .next("smalltiles_light")
                .model(ModelTemplates.cubeEldritch())
            .next("stand_creeper")
                .model(ModelTemplates.columnEldritch("temple"))
            .next("stand_mosaic")
                .model(ModelTemplates.columnEldritch("temple"))
            .build(b -> b.strength(1.5F).explosionResistance(10.0F).sound(SoundType.STONE));

    public static final Map<String, BlockEntry<BlockCarvable>> TEMPLE_MOSSY = _FACTORY.newType(Material.STONE, "templemossy")
            .setGroup(TEMPLE1)
            .setGroupName("")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .variation("cobble") //TODO fix ctm and model
                .model(ModelTemplates.cubeEldritch())
            .next("ornate")
                .model(ModelTemplates.cubeEldritch())
            .next("plate")
                .model(ModelTemplates.cubeEldritch())
            .next("plate_cracked") //TODO fix ctm and model
                .model(ModelTemplates.cubeEldritch())
            .next("bricks")
                .model(ModelTemplates.cubeEldritch())
            .next("large_bricks")
                .model(ModelTemplates.cubeEldritch())
            .next("weared_bricks")
                .model(ModelTemplates.cubeEldritch())
            .next("disarray_bricks")
                .model(ModelTemplates.cubeEldritch())
            .next("column")
                .model(ModelTemplates.columnEldritch("temple"))
            .next("stand")
                .model(ModelTemplates.columnEldritch("temple"))
            .next("tiles")
                .model(ModelTemplates.cubeEldritch())
            .next("smalltiles")
                .model(ModelTemplates.cubeEldritch())
            .next("tiles_light")
                .model(ModelTemplates.cubeEldritch())
            .next("smalltiles_light")
                .model(ModelTemplates.cubeEldritch())
            .next("stand_creeper")
                .model(ModelTemplates.columnEldritch("temple"))
            .next("stand_mosaic")
                .model(ModelTemplates.columnEldritch("temple"))
            .build(b -> b.strength(1.5F).explosionResistance(10.0F).sound(SoundType.STONE));

    public static final Map<String, BlockEntry<BlockCarvable>> TYRIAN = _FACTORY.newType(Material.METAL, "tyrian")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .initialProperties(() -> Blocks.IRON_BLOCK)
            .color(MaterialColor.TERRACOTTA_CYAN)
            .variation("shining")
                .recipe((prov, block) -> new ShapedRecipeBuilder(block, 32)
                        .pattern("SSS").pattern("SXS").pattern("SSS")
                        .define('S', Tags.Items.STONE)
                        .define('X', Tags.Items.INGOTS_IRON)
                        .unlockedBy("has_iron", prov.has(Tags.Items.INGOTS_IRON))
                        .save(prov))
            .next("tyrian")
            .next("chaotic")
            .next("softplate")
            .next("rust")
            .next("elaborate")
            .next("routes")
            .next("platform")
            .next("platetiles")
            .next("diagonal")
            .next("dent")
            .next("blueplating")
            .next("black")
            .next("black2")
            .next("opening")
            .next("plate") // FIXME temporary texture
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> VALENTINES = _FACTORY.newType(Material.STONE, "valentines")
            .recipe((prov, block) -> new ShapedRecipeBuilder(block, 32)
                    .pattern("SSS").pattern("SXS").pattern("SSS")
                    .define('S', Tags.Items.STONE)
                    .define('X', Tags.Items.DYES_PINK)
                    .unlockedBy("has_dye", prov.has(Tags.Items.DYES_PINK))
                    .save(prov)) //TODO selective recipe
            .variation("1")
            .next("2")
            .next("3")
            .next("4")
            .next("5")
            .next("6")
            .next("7")
            .next("8")
            .next("9")
            .next("companion")
            .build(b -> b.strength(1.5F).explosionResistance(20.0F).sound(SoundType.STONE));

    public static final TagKey<Block> VOIDSTONE1 = BlockTags.create(new ResourceLocation(Reference.MOD_ID, "voidstone"));

    public static final Map<String, BlockEntry<BlockCarvable>> VOIDSTONE = _FACTORY.newType(Material.STONE, "voidstone")
            .setGroup(VOIDSTONE1)
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .recipe((prov, block) ->  {
                new ShapedRecipeBuilder(block, 16)
                        .pattern(" E ").pattern("OOO").pattern(" E ")
                        .define('E', Items.ENDER_EYE)
                        .define('O', Tags.Items.OBSIDIAN)
                        .unlockedBy("has_eye", prov.has(Items.ENDER_EYE))
                        .save(prov);
                //TODO fix multi recipe
//                new ShapedRecipeBuilder(block, 48)
//                        .pattern(" P ").pattern("PEP").pattern(" P ")
//                        .define('E', Items.ENDER_EYE)
//                        .define('P', Blocks.PURPUR_BLOCK)
//                        .unlockedBy("has_eye", prov.has(Items.ENDER_EYE))
//                        .save(prov, new ResourceLocation(Chisel.MOD_ID, "voidstone2"));
            })
            .variation(VariantTemplates.RAW)
            .variation("quarters")
            .next("smooth")
            .next("skulls")
            .next("rune")
            .next("metalborder")
            .next("eye")
            .next("bevel")
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> VOIDSTONE_ENERGISED = _FACTORY.newType(Material.STONE, "voidstone/animated")
            .setGroup(VOIDSTONE1)
            .setGroupName("")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .variation(VariantTemplates.RAW)
                .model(ModelTemplates.cubeLayerTopshaded("block/voidstone/animated/background"))
            .variation("quarters")
                .model(ModelTemplates.cubeLayerTopshaded("block/voidstone/animated/background"))
            .next("smooth")
                .model(ModelTemplates.cubeLayerTopshaded("block/voidstone/animated/background"))
            .next("skulls")
                .model(ModelTemplates.cubeLayerTopshaded("block/voidstone/animated/background"))
            .next("rune")
                .model(ModelTemplates.cubeLayerTopshaded("block/voidstone/animated/background"))
            .next("metalborder")
                .model(ModelTemplates.cubeLayerTopshaded("block/voidstone/animated/background"))
            .next("eye")
                .model(ModelTemplates.cubeLayerTopshaded("block/voidstone/animated/background"))
            .next("bevel")
                .model(ModelTemplates.cubeLayerTopshaded("block/voidstone/animated/background"))
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> VOIDSTONE_RUNIC = _FACTORY.newType(Material.STONE, "voidstone/runes")
            .setGroup(VOIDSTONE1)
            .setGroupName("")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .variation("black")
            .next("red")
            .next("green")
            .next("brown")
            .next("blue")
            .next("purple")
            .next("cyan")
            .next("lightgray")
            .next("pink")
            .next("lime")
            .next("yellow")
            .next("lightblue")
            .next("magenta")
            .next("orange")
            //.next("white")
            .build();

    public static final Map<String, BlockEntry<BlockCarvable>> WATERSTONE = _FACTORY.newType(Material.STONE, "waterstone")
            .applyTag(BlockTags.MINEABLE_WITH_PICKAXE)
            .applyTag(BlockTags.NEEDS_STONE_TOOL)
            .addTag(ChiselCompatTags.WATERSTONE)
            .initialProperties(() -> Blocks.STONE)
            .recipe((prov, block) -> new ShapedRecipeBuilder(block, 8)
                    .pattern("***").pattern("*X*").pattern("***")
                    .define('*', Blocks.STONE)
                    .define('X', Items.WATER_BUCKET)
                    .unlockedBy("has_stone", prov.has(Items.STONE))
                    .save(prov))
            .variation("cracked")
                .model(ModelTemplates.fluidCube("water"))
            .next("soft_bricks").localizedName("Weathered Bricks")
                .model(ModelTemplates.fluidCube("water"))
            .next("cracked")
                .model(ModelTemplates.fluidCube("water"))
            .next("triple_bricks").localizedName("Wide Bricks")
                .model(ModelTemplates.fluidCube("water"))
            .next("encased_bricks")
                .model(ModelTemplates.fluidPassCube("water"))
            .next("braid")
                .model(ModelTemplates.fluidCube("water"))
            .next("array").localizedName("Arrayed Bricks")
                .model(ModelTemplates.fluidPassCube("water"))
            .next("tiles_large").localizedName("Big Tile")
                .model(ModelTemplates.fluidPassCube("water"))
            .next("tiles_small").localizedName("Small Tiles")
                .model(ModelTemplates.fluidCube("water"))
            .next("chaotic_medium").localizedName("Disordered Tiles")
                .model(ModelTemplates.fluidCube("water"))
            .next("chaotic_small").localizedName("Small Disordered Tiles")
                .model(ModelTemplates.fluidCube("water"))
            .next("dent")
                .model(ModelTemplates.fluidPassCube("water"))
            .next("french_1")
                .model(ModelTemplates.fluidCube("water"))
            .next("french_2")
                .model(ModelTemplates.fluidCube("water"))
            .next("jellybean")
                .model(ModelTemplates.fluidPassCube("water"))
            .next("layers")
                .model(ModelTemplates.fluidCube("water"))
            .next("mosaic")
                .model(ModelTemplates.fluidPassCube("water"))
            .next("ornate")
                .model(ModelTemplates.fluidCube("water"))
            .next("panel")
                .model(ModelTemplates.fluidCube("water"))
            .next("road")
                .model(ModelTemplates.fluidCube("water"))
            .next("slanted")
                .model(ModelTemplates.fluidPassCube("water"))
            .next("zag")
                .model(ModelTemplates.fluidPassCube("water"))
            .next("circularct").localizedName("Circular")
                .model(ModelTemplates.fluidCubeCTM("water", "circular"))
            .next("weaver").localizedName("Celtic")
                .model(ModelTemplates.fluidPassCube("water"))
            .next("solid_bricks").localizedName("Bricks")
                .model(ModelTemplates.fluidCube("water"))
            .next("small_bricks")
                .model(ModelTemplates.fluidCube("water"))
            .next("circular")
                .model(ModelTemplates.fluidCube("water"))
            .next("tiles_medium").localizedName("Tiles")
                .model(ModelTemplates.fluidPassCube("water"))
            .next("pillar")
                .model(ModelTemplates.fluidPassColume("water"))
            .next("twisted")
                .model(ModelTemplates.fluidPassColume("water"))
            .next("prism")
                .model(ModelTemplates.fluidCube("water"))
            .next("chaotic_bricks").localizedName("Trodden Bricks")
                .model(ModelTemplates.fluidPassCube("water"))
            .next("cuts")
                .model(ModelTemplates.fluidPassCube("water"))
            .build(b -> b.strength(4.0F).explosionResistance(50.0F).sound(SoundType.STONE));

    public static final Map<DyeColor, Map<String, BlockEntry<BlockCarvable>>> WOOL = Arrays.stream(DyeColor.values())
            .collect(Collectors.toMap(Function.identity(), color -> _FACTORY.newType(Material.WOOL, "wool/" + (color.getSerializedName()))
                    .addBlock(new ResourceLocation(color.getSerializedName() + "_wool")) // TODO improve this copied RL construction
                    .applyTag(BlockTags.WOOL)
                    .setGroupName(RegistrateLangProvider.toEnglishName(color.getSerializedName()) + " Wool")
                    .initialProperties(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(color.getSerializedName() + "_wool")))
                    .variation("legacy")
                    .next("llama")
                    .build()));
    
    public static void init() {}

    private static class BlockCreators {

        private static final BlockCreator<BlockCarvable> redstoneCreator = (props, data) -> new BlockCarvable(props, data) {
            @Override
            @Deprecated
            public boolean isSignalSource(BlockState state) {
                return true;
            }

            @Override
            @Deprecated
            public int getSignal(BlockState state, BlockGetter reader, BlockPos pos, Direction direction) {
                return 15;
            }
        };
    }
}
